### ISSUE TITLE
Race condition in MIG health signals

### ISSUE THREAD

**Issue by cristinaleonr** [m-lab/locate#157]
Managed Instance Groups (MIGs) are groups of VMs treated as a single instance. All instances in the group share a common hostname in the Heartbeat (https://github.com/m-lab/locate/pull/117). 

If any one VM in the group sends an unhealthy signal to the Locate, the entire group (i.e., hostname) will (temporarily) be marked as unhealthy (even if the others are healthy). Similarly, if there is at least one instance that is healthy, the whole group will (temporarily) be marked as healthy (even if others are unhealthy).

**Comment by nkinkade** [comment]
A new thought we discussed today at the Platform meeting is for the heartbeat service to query load balancer health rather than querying the local pod services directly. The reasoning is that load balancers already have health checks configured for all of their backend instances.  We should be able to largely, or even completely, implement all the current HB checks in various health checks.  Backend instances are managed by the cloud provider and should not be treated like snowflakes.

For example:

```
$ gcloud compute backend-services get-health mlab1-pdx0t-mlab-sandbox-measurement-lab-org --region us-west1 --project mlab-sandbox
---
backend: https://www.googleapis.com/compute/v1/projects/mlab-sandbox/regions/us-west1/instanceGroups/mlab1-pdx0t-mlab-sandbox-measurement-lab-org
status:
  healthStatus:
  - forwardingRule: https://www.googleapis.com/compute/v1/projects/mlab-sandbox/regions/us-west1/forwardingRules/mlab1-pdx0t-mlab-sandbox-measurement-lab-org
    forwardingRuleIp: 34.127.102.87
    healthState: HEALTHY
    instance: https://www.googleapis.com/compute/v1/projects/mlab-sandbox/zones/us-west1-a/instances/mlab1-pdx0t-mlab-sandbox-measurement-lab-org-28z4
    ipAddress: 10.2.0.104
    port: 80
  - forwardingRule: https://www.googleapis.com/compute/v1/projects/mlab-sandbox/regions/us-west1/forwardingRules/mlab1-pdx0t-mlab-sandbox-measurement-lab-org
    forwardingRuleIp: 34.127.102.87
    healthState: HEALTHY
    instance: https://www.googleapis.com/compute/v1/projects/mlab-sandbox/zones/us-west1-b/instances/mlab1-pdx0t-mlab-sandbox-measurement-lab-org-gr1t
    ipAddress: 10.2.0.2
    port: 80
  - forwardingRule: https://www.googleapis.com/compute/v1/projects/mlab-sandbox/regions/us-west1/forwardingRules/mlab1-pdx0t-mlab-sandbox-measurement-lab-org
    forwardingRuleIp: 34.127.102.87
    healthState: HEALTHY
    instance: https://www.googleapis.com/compute/v1/projects/mlab-sandbox/zones/us-west1-c/instances/mlab1-pdx0t-mlab-sandbox-measurement-lab-org-1ff7
    ipAddress: 10.2.0.15
    port: 80
  kind: compute#backendServiceGroupHealth
```

Presumably, as long as one backend instance is passing health checks then the instance group / load balancer as a whole can be flagged as healthy.

https://cloud.google.com/compute/docs/reference/rest/v1/backendServices/getHealth

We discussed passing a new flag to the heartbeat service to trigger it to query backend service health rather than local service health. We also discussed having heartbeat start without any special flags, discover its environment, and then run tests accordingly depending on whether it is load balancer or running on a standalone VM.
