### ISSUE TITLE
Request Token for Specified Server

### ISSUE THREAD

**Issue by Daemonslayer2048** [m-lab/locate#35]
With the recent news of moving to an access token for test authentication from what I can see this looks to break the use of testing to a specified host on the public m-lab infrastructure. 
Would it be possible to set up an endpoint to request a token that could then be used on a specified public server? 

The use case would be something like: 
1. I know the specific server I would like to test to
2. I want to test to a server more distant outside of my region (assumption being I already know the hostname)

I think both would be valid test cases, testing to the same server every so often would be useful for tracking internet performance over a longer period of time while trying to keep variables like the server in use and distance to that server the same. The second use case is beneficial for determining how much your bandwidth drops off based on distance. While distance is not necessarily the determining factor for bandwidth, traveling across different ASNs absolutely impacts your effective bandwidth. 

Thoughts?

**Comment by critzo** [comment]
Thanks for posting this issue here @Daemonslayer2048 . Following up with what I shared in our support@ email thread, I think that the Locate API should provide for more options than simply the "nearest" server. For example, mlab-ns provided the ability to select a server in a particular country, and many more options. The outline of [planned features](https://github.com/m-lab/locate/blob/master/USAGE.md#locate-servers-near-the-client) doesn't include many of the previously available features of [mlab-ns](https://github.com/m-lab/mlab-ns/blob/master/DESIGN_DOC.md#url-format).

Another use case we discussed on support@ was how Locate and ndt-server interact. If ndt-server only conducts an ndt7 test with a client that presents an access token, users who have self-provisioned one or more ndt-server instances will need to be able to disable the access token validation in their instances. If I'm incorrect about that, then we need documentation about how clients like `ndt7-client-go` can conduct a test to a self-provisioned server.

**Comment by Daemonslayer2048** [comment]
@critzo I think you are right on the money. If a key could be obtained for any server requested this would also give custom clients some ability to implement their own way of deciding what server to test against. 

For example: If I want to run a test against a specific area (city, state, or zip) I could do so, assuming I know what servers exist, and where, by requesting a token for a known host. 

This would take away the need for the Locate API to handle every possible scenario and place that on the client (if only until the Locate API implements that functionality). I think this would make things more flexible especially for clients that would wish to implement their own server selection logic and preserve the testing limits imposed on the public infrastructure. 

Having the option to disable the token requirement would also be nice for self-provisioned instances too.

**Comment by critzo** [comment]
@Daemonslayer2048 @stephen-soltesz has confirmed that in `ndt-server` there is a default to not require access token. So for your self-hosted `ndt-servers` your clients will not need any access token. The question is still open about new features of the M-Lab Locate service to enable your clients to test against M-Lab servers that are remote, not "nearest".

**Comment by Daemonslayer2048** [comment]
Awesome, thanks for the update @critzo

**Comment by stephen-soltesz** [comment]
@Daemonslayer2048  We enthusiastically agree that there are use cases not yet supported by the Locate API v2. And, I'm thrilled to learn that this is a use case that others would like. Use cases currently supported by mlab-ns (locate v1) and ndt5 (such as direct server targeting) will continue to be supported for the foreseeable future until there is a migration path.

In the near term, ndt7 and Locate API v2 releases are tightly coupled. Practically, this means that after we require access tokens for ndt7, we will only support the "nearest" location for ndt7 measurements. These features address specific shortcomings that cannot be addressed for legacy deployments based on ndt5 and mlab-ns. New features take time to develop and deploy. The combination of ndt7, Locate v2, and access tokens have been in progress since April. We will make sure that "chosen site" or "direct server" like functionality is on the roadmap for the Locate v2 API.

**Comment by Daemonslayer2048** [comment]
So for at least some time, there will be no way to run tests to NDTv7 servers that are not returned by the Locate v2 API correct? I just want to make sure I am correct about that as that will cause some fairly significant issues for me.

**Comment by stephen-soltesz** [comment]
@Daemonslayer2048 can you say more about how you arrived at the current strategy you're using? Did anyone from M-Lab recommend directly targeting servers? I don't want to pull the rug out from under your work. At the same time, to my knowledge, M-Lab has not promoted our support for the direct-server model for ndt7. Direct server measurements are still possible using ndt5-client-go or other ndt5 clients.

For some background, the reason that we are starting with this approach with ndt7 is that in April we noticed that 1000's of clients were directly targeting ~13 servers using a highly synchronized schedule, roughly every hour. These measurements were interfering with each other and other measurements. We still see evidence of synchronized scheduling though less severe. When clients must contact the locate API first, there is an option to introduce policies that manage that usage pattern. At the end of the day, this is about safeguarding measurement quality for the M-lab platform and the measurements performed by clients like yours.

**Comment by Daemonslayer2048** [comment]
No one from M-Lab pointed out using individual servers. We were trying to implement our own server selection process as we have done so before but with NDTv7. The problem with using NDTv5 is it lacks specific data that we need, mainly total bytes sent and recieved. 

> April we noticed that 1000's of clients were directly targeting ~13 servers using a highly synchronized schedule, roughly every hour

Sounds like a mass cron job setup. My setup is no where near that scale and not running based on cron. I can imagine thats quite the problem. 

Not to push this too hard but the api could also be used to allow custom server selection and still reject a client. The clients would just be expected to understand a rejection from the api to access a specific server. If I remember correctly this error is already built into the locate api if no server is currently available.

**Comment by arturmusin** [comment]
@critzo , after communicating with M-Lab support I've been told that M-Lab will start enforcing using tokens in NDT v7 protocol. 
Our company is developing VPN client with SpeedTest feature integrated. Let me describe you our use-case scenario in our product.

1. Application retrieves a list of the nearest servers and populated dropbox with them
2. a user runs speed test **without VPN tunnel turned on** and gets the result
3. a user **turns on VPN tunnel** in our client and runs runs speed test against the same server to compare connection speed with and without VPN tunnel
4. a client gets "token expired" exception since **more than 1 minute have passed** since between 2nd and 3rd step.

Would it be possible to increase the expiration period of the token and set it at lease to 5-10 minutes instead of 1 minute?

**Comment by stephen-soltesz** [comment]
@arturmusin access tokens are intended to be single-use. The server may refuse to accept duplicate tokens in the future. For your use-case, clients should contact the Locate API again to get a new set of access tokens for the second measurement. Because access tokens should be single-use, we do not plan to increase the access token expiration at this time for NDT.

**Comment by darkk** [comment]
[VPNalyzer](https://vpnalyzer.org/) has a use-case that is very similar to the one @arturmusin has: we want to measure bandwidth against the approximately same test-point via two different network paths: VPN link and non-VPN link.

We currently get `X-Locate-Clientlatlon` from the query to `/v2/nearest/ndt/ndt7` and add those coordinates as `/v2/nearest/ndt/ndt7?lat=${lat}&lon=${lon}` query, so the locate API responds with a token for a  server that is somewhat _"close"_ to the server we've used for the previous ndt7 run.

However, `lat` & `lon` options are not documented at https://github.com/m-lab/locate/blob/master/USAGE.md So, I wonder, is this feature intended just for debugging or is it something that might be set in stone and documented? I also have the same question about `X-Locate-Clientlatlon` header. The header is explicitly mentioned, but it's not explicitly documented as a part of API. Is it something that we can rely upon?

**Comment by stephen-soltesz** [comment]
@darkk We should document support for the lat/lon option. That will be supported long term.

The `X-Locate-Clientlatlon` header was added to help debugging clients that appear to receive incorrect geolocation hints from AppEngine or other sources. I'm reluctant to commit to supporting these. However, I can say that we won't change these without providing a replacement, such as a new field in the response structure for "effective client location".

**Comment by stephen-soltesz** [comment]
@vps-eric what functionality are you interested in?
