### ISSUE TITLE
[Question] Locate API Tokens

### ISSUE THREAD

**Issue by Daemonslayer2048** [m-lab/locate#41]
Given the move to the Locate API I noticed the API returns a token per server. I am curious and looking for more details regarding what counts as actually consuming the token? I assume the token is consumed when the test acutally starts and the token is sent to the server in question, but I am just looking for confrimation.

**Comment by stephen-soltesz** [comment]
Yes, it's correct to say the ndt server has "consumed" the token after the measurement starts.

The intention is for access tokens to be single-use. Practically, access tokens will expire after about two minutes.

Currently, the implementation of the ndt server does not prevent reuse, but we may need to change that in the future. Also, clients should not retry a rejected connection with the same token, because the server may be overloaded or otherwise unavailable. In that situation, clients should try the next server in the list returned by the Locate API. 

Is there a particular use-case you have in mind?

**Comment by Daemonslayer2048** [comment]
No particular use case, I am trying to make sure I understand fully the API. Would it also be accurate to say the rate limit of tests is based on public IP?

**Comment by stephen-soltesz** [comment]
Yes, that's basically correct. We rate limit largely to prevent abuse and too frequent testing does not actually provide more information for users or M-Lab (which must manage finite resources). Our best published advice for integrations and test frequency is https://www.measurementlab.net/develop/#best-practices-on-test-scheduling-and-frequency

**Comment by Daemonslayer2048** [comment]
Thank you for all the responses, and the link. That was what I needed.
